import { FC } from 'react';
import { Link } from 'react-router';
import { REPO_URL } from '../../config/constants';
import { CONTACT_EMAIL, LegalLayout, OPERATOR, POSTAL_ADDRESS } from './LegalLayout';

export const TermsPage: FC = () => (
  <LegalLayout title="Terms of service" updated="2 September 2026">
    <p>
      These terms are the agreement between you and {OPERATOR} ("Sage", "we") for using Talleyrand
      at talleyrand.app. By signing in, you agree to them. Please also read the{' '}
      <Link to="/privacy">privacy policy</Link>, which says what we store and where it goes.
    </p>
    <p>
      The software behind Talleyrand is open source under the{' '}
      <a href={`${REPO_URL}/blob/main/LICENSE`} target="_blank" rel="noopener noreferrer">
        MIT license
      </a>
      . These terms cover only the hosted service. If you run your own copy, the license governs
      instead.
    </p>

    <h2 id="who">1. Who can use Talleyrand</h2>
    <p>
      You must be at least 18 years old and have a Google account. You are responsible for
      everything done through your account. Your sign-in token and your API keys are kept in your
      browser, so keep the device you use secure and sign out on shared computers.
    </p>

    <h2 id="keys">2. Your API keys</h2>
    <p>
      Talleyrand does not come with a model. You bring an OpenAI API key, and optionally an
      Anthropic one, and every model call is made with your key and billed to your account with that
      provider. That means:
    </p>
    <ul>
      <li>
        you pay the provider directly for what the model does, including for background work you
        started and then walked away from, and those charges are your responsibility;
      </li>
      <li>
        your use of each provider is governed by its own terms, and you must comply with them;
      </li>
      <li>
        we pass your key through to the provider and never store it, but it is a secret: if you
        think it has leaked, revoke it with the provider;
      </li>
      <li>
        we are not responsible for a provider's prices, outages, refusals, rate limits, or changes.
      </li>
    </ul>

    <h2 id="content">3. Your content</h2>
    <p>
      Your cases belong to you: the brief, your questions, your notes and reactions, and the
      documents you attach. You give us permission to store, process, and transmit them as far as
      running the service requires: keeping them in the database, sending them to the model provider
      you chose, and showing them back to you. When you share a case, you also give us permission to
      show it to anyone with the link and to copy it into their account when they ask.
    </p>
    <p>
      You must have the right to upload what you upload. Do not attach documents you are not allowed
      to share, and do not put other people's private information into a case without their
      permission.
    </p>
    <p>
      Answers written by the models are yours to use, subject to your provider's terms. We claim no
      rights in them.
    </p>

    <h2 id="sharing">4. Shared cases and copies</h2>
    <p>
      Sharing is by link. Anyone with the link can read the case, attached documents included, and
      copy it. You can stop sharing at any time and the link stops working at once, but copies
      others already made are theirs and stay with them. A case someone shared with you is theirs:
      read it, copy it, and build on it, but do not misuse it.
    </p>

    <h2 id="ai">5. Answers are generated by AI</h2>
    <p>
      The answers, suggestions, summaries, and reports are written by language models. They can be
      wrong, out of date, or invented, and they can state made-up facts with confidence. They are
      not medical, legal, financial, or other professional advice. Check anything you intend to rely
      on. Answers may link to third-party web pages, which we do not control.
    </p>

    <h2 id="use">6. Acceptable use</h2>
    <p>
      Do not use Talleyrand to break the law, to harass or harm others, or to store content that is
      illegal where you or we live. Do not try to get around the rate limits, to reach other
      people's private cases, to disrupt the service, or to load it in ways it is not built for,
      such as scraping shared cases at scale. If you find a security problem, please tell us at{' '}
      <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> rather than exploiting it.
    </p>

    <h2 id="availability">7. Availability and limits</h2>
    <p>
      Talleyrand is free, new, and run by a small nonprofit. We do not promise that it will always
      be available or free of errors, and we may change or remove features and adjust limits at any
      time. A case cannot grow beyond about 15 MB, and each account is rate-limited. If we ever
      close the service, we will announce it on talleyrand.app in advance so that you can export
      your cases.
    </p>

    <h2 id="ending">8. Ending things</h2>
    <p>
      You can stop using Talleyrand whenever you like: export what you want to keep, delete your
      cases, and sign out. We may suspend or end your access if you break these terms or put the
      service or other users at risk. Where we can, we will tell you why.
    </p>

    <h2 id="warranty">9. No warranty</h2>
    <p>
      Talleyrand is provided "as is" and "as available", without warranties of any kind, express or
      implied, including fitness for a particular purpose and non-infringement, to the fullest
      extent the law allows.
    </p>

    <h2 id="liability">10. Limitation of liability</h2>
    <p>
      To the fullest extent the law allows, Sage is not liable for indirect, incidental,
      consequential, or punitive damages, or for lost data, profits, or business, arising from your
      use of Talleyrand, including from the accuracy of any answer, charges from your model
      provider, or content in shared cases. Our total liability for all claims connected with the
      service is limited to 50 US dollars. Some jurisdictions do not allow these exclusions; there,
      they apply as far as the law permits, and nothing here limits liability that cannot be limited
      by law.
    </p>

    <h2 id="law">11. Governing law</h2>
    <p>
      These terms are governed by the laws of the State of Delaware, United States, without regard
      to its conflict-of-law rules, and disputes are to be brought in the state or federal courts
      located in Delaware. If you are a consumer in the European Union or the United Kingdom, you
      keep the protection of the mandatory consumer laws of your country and may bring a claim in
      your local courts.
    </p>

    <h2 id="changes">12. Changes to these terms</h2>
    <p>
      We may update these terms. When we do, we will change the date at the top and, for changes
      that matter, tell you in the app before they take effect. Using Talleyrand after a change
      means you accept the new terms.
    </p>

    <h2 id="contact">13. Contact</h2>
    <p>
      {OPERATOR}, {POSTAL_ADDRESS}. Email <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      The source code and issue tracker are on{' '}
      <a href={REPO_URL} target="_blank" rel="noopener noreferrer">
        GitHub
      </a>
      . Suggestions you send us may be used without any obligation to you.
    </p>
  </LegalLayout>
);
